#!/bin/bash
[ "true" == "${IGNORE_REPO_UPDATE}" ] || apt-get update

# Install all necessary packages for Arduino development
apt-get install -y arduino python-pip build-essential vim python-dev

# Install command-line tools for Arduino build system
#
pip install ino

# Avoid library compilation error led by Robot_Control.
#
rm -rf /usr/share/arduino/libraries/Robot_Control
