#!/bin/bash

source $(dirname $0)/helpers

# Initiate Package Installation
#
initiate

if [ "" == "$(which node)" ]; then
	# Refet to https://github.com/joyent/node/wiki/installing-node.js-via-package-manager
	wget -O- -q https://deb.nodesource.com/setup | sudo bash -

	# Install all necessary packages for Arduino development
	install_utils "nodejs" || exit 1
fi

install_python_pkgs "httpie" || exit 1
install_nodejs_utils "LiveScript coffee-script pm2 forever"
