#!/bin/bash

source $(dirname $0)/helpers

# Initiate Package Installation
#
initiate

# Install packages
#
install_utils "git subversion build-essential imagemagick v4l-utils" || exit 1
install_libs "jpeg png" || exit 1


TMP=$(pwd)
if [ ! -d "/opt/mjpg-streamer" ]; then
	cd /tmp
	git clone https://github.com/yagamy4680/mjpg-streamer.git
	cd mjpg-streamer/mjpg-streamer-experimental
	make clean
	make
	mkdir -p /opt/mjpg-streamer
	cp mjpg_streamer /opt/mjpg-streamer/
	cp *.so /opt/mjpg-streamer/
	cp -R www/ /opt/mjpg-streamer
	cd ${TMP}
fi
