#!/bin/bash

source $(dirname $0)/helpers

# Initiate Package Installation
#
initiate

# Install all necessary packages for Arduino development
#
install_utils "wireless-tools iw wpasupplicant" || exit 1
