#!/bin/bash

source $(dirname $0)/helpers

# Initiate Package Installation
#
initiate

# Install all necessary packages for Arduino development
#
install_utils "build-essential vim python-dev python-pip picocom arduino" || exit 1

# Install command-line tools for Arduino build system
#
install_python_pkgs "ino"

# Avoid library compilation error led by Robot_Control.
#
rm -rf /usr/share/arduino/libraries/Robot_Control
