#!/bin/bash

source $(dirname $0)/helpers

# Initiate Package Installation
initiate

# Install all necessary packages for building BlueZ
#
install_utils "build-essential git socat" || exit 1

# Install required libraries for building BlueZ
#
install_libs "usb dbus glib2 udev ical readline bluetooth" || exit 1


if [ "" == "$(which hciconfig)" ]; then
	# Build BlueZ and install.
	cd /opt
	git clone https://github.com/yagamy4680/bluepy.git
	cd bluepy
	BLUEZ_INSTALLATION=true ./build.sh
fi


# With py-gobject and dbus modules, the bluez python sample
# codes can work normally.
#
if [ "true" == "${INSTALL_PYTHON_PACKAGES}" ]; then
	install_utils "python-pip python-dev python-gobject python-dbus" || exit 1
	install_python_pkgs "pyserial rainbow_logging_handler" || exit 1
fi
