#!/bin/bash

# Detect the Linux distribution
#
OS="linux"
[ "" == "$(uname -a | grep -i ubuntu)" ] || OS="ubuntu"
[ "" == "$(uname -a | grep -i darwin)" ] || OS="darwin"
[ "" == "$(lsb_release -a | grep -i Distributor | grep -i ubuntu)" ] || OS="ubuntu"

# Detect hostname
[ "" == "${BOX_NAME}" ] && BOX_NAME=$(hostname)

# Detect current directory
#
TMP=$(pwd)
CURRENT=$(dirname $0)
cd ${CURRENT}
CURRENT=$(pwd)
cd ${TMP}

# Fetch command
#
FETCH_CMD="cat ${CURRENT}/${OS}"

# Detect `packages.conf` file for packages to be installed.
#
PACKAGE_LIST_FILE="${CURRENT}/_${BOX_NAME}/packages.conf"
if [ ! -f "${PACKAGE_LIST_FILE}" ]; then
	echo "[warning] no packages to install, because of missing ${PACKAGE_LIST_FILE} ..."
	exit 0
fi
PKGS=($(cat ${PACKAGE_LIST_FILE} | sed -e 's/^ *//' | sed -e 's/ *$//' | sed 's/#.*$//g' | grep -v "^$"))

if [ "" != "EXTRA_PKGS" ]; then
	X=$(echo "${EXTRA_PKGS}" | tr ',' ' ')
	read -a EXTRA_PKGS <<<$X
	PKGS=("${PKGS[@]}" "${EXTRA_PKGS[@]}")
fi

echo "installing following packages: "
for i in "${PKGS[@]}"
do
	echo -e "\t$i"
done

# Installation on Ubuntu system
#
if [ "ubuntu" == "${OS}" ]; then
	for i in "${PKGS[@]}"
	do
		echo "${FETCH_CMD}/install_$i | /bin/bash"
		${FETCH_CMD}/install_$i | /bin/bash
	done
fi

if [ "linux" == "${OS}" ]; then
	echo "unspported OS: $(uname -a)"
	exit 1
fi
