#!/bin/bash

function check_executable {
	[ "" == "$(which $1)" ] && echo "missing $1 ..."
}

[ "" == "${BOX_NAME}" ] && BOX_NAME=$(hostname)

CURRENT=$(dirname $0)
cd ${CURRENT}
CURRENT=$(pwd)
cd ${TMP}

PKGS=($(cat ${CURRENT}/_${BOX_NAME}/packages.checks | sed -e 's/^ *//' | sed -e 's/ *$//' | sed 's/#.*$//g' | grep -v "^$"))
for i in "${PKGS[@]}"
do
	check_executable $i
done

