#!/bin/bash
#
# The script is used to reduce Vagrant box size.
#
# ------------------------------------------------------------

# Remove unnecessary packages
#
echo "Remove unnecessary apt packages"
apt-get -y --purge remove linux-headers-$(uname -r)
apt-get -y --purge autoremove
apt-get -y purge $(dpkg --list |grep '^rc' |awk '{print $2}')
apt-get -y purge $(dpkg --list |egrep 'linux-image-[0-9]' |awk '{print $3,$2}' |sort -nr |tail -n +2 |grep -v $(uname -r) |awk '{ print $2}')

# Unmount project
umount /vagrant

# Remove APT cache
#
if [ "true" == "${IGNORE_APT_CACHE_CLEANUP}" ]; then
	echo "Remove APT cache --> disabled"
else
	echo "Remove APT cache"
	apt-get clean -y -q
	apt-get autoclean -y -q
	find /var/lib/apt -type f | xargs rm -f
fi

# Zero free space to aid VM compression
echo "Zero free space to aim VM compression"
dd if=/dev/zero of=/EMPTY bs=1M
rm -f /EMPTY

echo 'Cleanup bash history'
unset HISTFILE
[ -f /root/.bash_history ] && rm /root/.bash_history
[ -f /home/vagrant/.bash_history ] && rm /home/vagrant/.bash_history

echo 'Cleanup log files'
find /var/log -type f | while read f; do echo -ne '' > $f; done;

echo 'Whiteout root'
count=`df --sync -kP / | tail -n1  | awk -F ' ' '{print $4}'`;
let count--
dd if=/dev/zero of=/tmp/whitespace bs=1024 count=$count;
rm /tmp/whitespace;

echo 'Whiteout /boot'
count=`df --sync -kP /boot | tail -n1 | awk -F ' ' '{print $4}'`;
let count--
dd if=/dev/zero of=/boot/whitespace bs=1024 count=$count;
rm /boot/whitespace;

swappart=`cat /proc/swaps | tail -n1 | awk -F ' ' '{print $1}'`
swapoff $swappart;
dd if=/dev/zero of=$swappart;
mkswap $swappart;
swapon $swappart;

rm -rf /tmp/*;
rm -rf /var/tmp/*;
