#!/bin/bash

[ "" == "${PROVIDER}" ] && export PROVIDER="virtualbox"

[ ! -f "$(dirname $0)/VERSION" ] && echo "missing file: $(dirname $0)/VERSION ..." && exit 1

# Make sure these plugins are installed before making Vagrant box
#
plugins=( "vagrant-cachier" "vagrant-vbguest" )
for p in "${plugins[@]}"
do
	[ "" == "$(vagrant plugin list | grep $p)" ] && echo "vagrant plugin install $p" && vagrant plugin install $p
done

NAME=$(basename $(pwd))
VERSION=$(cat "$(dirname $0)/VERSION" | sed /^[[:blank:]]*$/d | head -n1 | sed -e 's/^ *//' -e 's/ *$//')
BOX_FILE="${NAME}_${VERSION}_${PROVIDER}.box"
BOX_PATH="/tmp/${BOX_FILE}"

[ "" == "${HOST_SITE}" ] && export HOST_SITE="fog.local"
[ "" == "${HOST_USER}" ] && export HOST_USER="vagrant"
[ "" == "${HOST_PATH}" ] && export HOST_PATH="/home/vagrant/www/boxes"

HOST_URL="${HOST_USER}@${HOST_SITE}:${HOST_PATH}"
EXISTS=$(ssh ${HOST_USER}@${HOST_SITE} "find ${HOST_PATH}/${BOX_FILE}")

if [ "" != "${EXISTS}" ] && [ "-y" != "$1" ]; then
	echo "the box file ${BOX_FILE} exists on host server, are you sure to build same version box and overwrite the existed one?"
	read ANSWER
	if [ "yes" == "${ANSWER}" ] || [ "y" == "${ANSWER}" ]; then
		echo ""
	else
		exit 0
	fi
fi

echo -e "going to build box: "
echo -e "\tname: ${NAME}"
echo -e "\tversion: ${VERSION}"
echo -e ""

# Exit when error
set -e

# Make sure the default Vagrantfile is loaded before 
# Vagrantfile at current disk.
#
# Refer to https://docs.vagrantup.com/v2/vagrantfile/ to 
# understand `Load Order and Merge`
#
cp ../../scripts/Vagrantfile ~/.vagrant.d

# Destroy previous disk.
vagrant destroy -f

# Bring-up the box, and install all required software with provision scripts
time vagrant up --provider ${PROVIDER}

# Disable `vagrant-cachier` (so no cache folder is mounted) and bring-up again for disk-cleanup
[ "" == "$(vagrant plugin list | grep "vagrant-cachier")" ] && export IGNORE_APT_CACHE_CLEANUP="true" || export IGNORE_APT_CACHE_CLEANUP="false"
time vagrant ssh -c "sudo IGNORE_APT_CACHE_CLEANUP=${IGNORE_APT_CACHE_CLEANUP} /vagrant-boxes/scripts/cleanup_disk"

# Package the box
rm -f ${BOX_PATH}
time vagrant package --output=${BOX_PATH}

# Upload the box to host server
echo "upload box to ${HOST_SITE}"
scp ${BOX_PATH} ${HOST_URL}

# Delete the box file
rm -f ${BOX_PATH}
