# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Hostname for guest system
VBOX_NAME = File.basename(Dir.getwd)

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = VBOX_NAME

  # Share current repository at top.
  config.vm.synced_folder "../../", "/vagrant-boxes"

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ffuenf/ubuntu-14.04.1-server-amd64"

  # Enable `vagrant-cachier` to cache APT packages for multiple machine
  # environment.
  #
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :machine
    config.cache.auto_detect = true
  else
    # only display the tips on vagrant up
    if ARGV[0] == "up"
      puts "[information] recommended vagrant plugin 'vagrant-cachier' plugin was not found"
      puts "[information] 'vagrant-cachier' will speed up repeated provisioning operations"
      puts "[information] install the plugin with command 'vagrant plugin install vagrant-cachier'"
    end
  end

  # Invoke following scripts to install softwares
  #   - install_arduino.sh
  #   - install_bluez.sh
  #   - install_nodejs.sh
  #   - install_util.sh
  #   - install_wireless.sh
  #
  config.vm.provision "shell", inline: "sudo /vagrant-boxes/scripts/init.sh"
end
