#!/bin/bash

function install_nodejs {
	VERSION=$1
	shift
	cat $(nodenv root)/plugins/node-build/share/node-build/${VERSION} | sed 's/nodejs\.org/archives\.t2t\.io\/mirrors\/nodejs\.org/g' > /tmp/${VERSION}
	nodenv install /tmp/${VERSION}
	nodenv global ${VERSION}
	npm install -g $@
}

source /opt/dotfiles/.bashrc
MODULES="livescript browserify exorcist uglify-js prettyjson"

install_nodejs 0.10.41 ${MODULES}
install_nodejs 0.11.9 ${MODULES}
install_nodejs 0.12.9 ${MODULES}
install_nodejs 4.2.4 ${MODULES}
install_nodejs 5.3.0 ${MODULES}

nodenv global 4.2.4
