# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.require_version ">= 1.8.0"

# Hostname for guest system
VBOX_NAME = File.basename(Dir.getwd)

unless Vagrant.has_plugin?("vagrant-vbguest")
  raise "vagrant-vbguest is not installed!!"
end

# Project Root
#
PROJECT_ROOTDIR = File.expand_path("../../")
PROJECT_EXTERNAL_DIR = "#{PROJECT_ROOTDIR}/externals"

# Directories to be mounted at /opt under LinuxBox with `rsync` methodology
# for performance consideration.
#
OPT_RSYNC_DIRS = %W(
  #{PROJECT_EXTERNAL_DIR}/dotfiles
)



Vagrant.configure(2) do |config|

  config.vm.hostname = VBOX_NAME
  config.vm.box = "yagamy/docker-base"

  # Share current repository at top.
  config.vm.synced_folder "../../", "/vagrant-boxes"

  OPT_RSYNC_DIRS.each do |dir|
    if File.directory?(dir)
      name = File.basename(File.expand_path(dir))
      config.vm.synced_folder dir, "/opt/#{name}",
        type: "rsync",
        rsync__args: ["--verbose", "--rsync-path='sudo rsync'", "--archive", "--delete", "-z"]
    else
      puts "[warning] #{dir} does not exist!!"
    end
  end

  # Enable `vagrant-cachier` to cache APT packages for multiple machine
  # environment.
  #
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :machine
    config.cache.auto_detect = true
  else
    # only display the tips on vagrant up
    if ARGV[0] == "up"
      puts "[information] recommended vagrant plugin 'vagrant-cachier' plugin was not found"
      puts "[information] 'vagrant-cachier' will speed up repeated provisioning operations"
      puts "[information] install the plugin with command 'vagrant plugin install vagrant-cachier'"
    end
  end

  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
  end

  config.vm.provision "shell", inline: "/bin/bash /opt/dotfiles/bootstrap"
  config.vm.provision "shell", inline: "/bin/bash /vagrant/init_nodejs"
end

